# fly.toml app configuration file generated for iframetest-dogbreeds on 2024-09-02T16:13:36+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'iframetest-dogbreeds'
primary_region = 'syd'

[build]

[build.args]
    BP_KEEP_FILES = "nested/*"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
